In [9]:
%matplotlib inline

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_sas("DEMO_L.XPT")

Let's have a look at the dataset:

In [3]:
df

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,12.0,2.0,1.0,9.0,NaN,2.0,2.0,1.0,111.0,...,1.0,3.0,3.0,3.0,NaN,11147.192563,13459.129019,176.0,1.0,2.01
11929,142307.0,12.0,2.0,2.0,49.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,69419.620456,64962.328962,181.0,1.0,NaN
11930,142308.0,12.0,2.0,1.0,50.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32696.313477,44367.534132,183.0,2.0,1.95
11931,142309.0,12.0,2.0,1.0,40.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,30547.974564,46249.361849,176.0,1.0,3.11
11932,142310.0,12.0,2.0,2.0,80.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32753.585494,49647.225467,187.0,2.0,5.00

In [4]:
df.shape

(11933, 27)

The dataset has 11 933 rows and 27 columns.

In [5]:
df.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMDBORN4',
       'DMDYRUSR', 'DMDEDUC2', 'DMDMARTZ', 'RIDEXPRG', 'DMDHHSIZ', 'DMDHRGND',
       'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR',
       'SDMVSTRA', 'SDMVPSU', 'INDFMPIR'],
      dtype='object')

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
SEQN,11933.0,136344.000000,3444.904716,1.303780e+05,1.333610e+05,136344.00000,139327.000000,142310.000000
SDDSRVYR,11933.0,12.000000,0.000000,1.200000e+01,1.200000e+01,12.00000,12.000000,12.000000
RIDSTATR,11933.0,1.742479,0.437287,1.000000e+00,1.000000e+00,2.00000,2.000000,2.000000
RIAGENDR,11933.0,1.532808,0.498943,1.000000e+00,1.000000e+00,2.00000,2.000000,2.000000
RIDAGEYR,11933.0,38.317858,25.601990,5.397605e-79,1.300000e+01,37.00000,62.000000,80.000000
RIDAGEMN,377.0,11.628647,6.805429,5.397605e-79,6.000000e+00,11.00000,17.000000,24.000000
RIDRETH1,11933.0,3.104584,1.076346,1.000000e+00,3.000000e+00,3.00000,4.000000,5.000000
RIDRETH3,11933.0,3.320540,1.518379,1.000000e+00,3.000000e+00,3.00000,4.000000,7.000000
RIDEXMON,8860.0,1.520203,0.499620,1.000000e+00,1.000000e+00,2.00000,2.000000,2.000000
RIDEXAGM,2787.0,121.908504,67.158655,5.397605e-79,6.600000e+01,122.00000,179.500000,239.000000
DMQMILIZ,8301.0,1.916998,0.282376,1.000000e+00,2.000000e+00,2.00000,2.000000,7.000000
DMDBORN4,11914.0,1.157378,0.364172,1.000000e+00,1.000000e+00,1.00000,1.000000,2.000000
DMDYRUSR,1875.0,7.334933,15.829158,1.000000e+00,3.000000e+00,6.00000,6.000000,99.000000
DMDEDUC2,7794.0,3.804978,1.153750,1.000000e+00,3.000000e+00,4.00000,5.000000,9.000000
DMDMARTZ,7792.0,1.778491,3.101080,1.000000e+00,1.000000e+00,1.00000,2.000000,99.000000
RIDEXPRG,1503.0,2.236860,0.485254,1.000000e+00,2.000000e+00,2.00000,3.000000,3.000000
DMDHHSIZ,11933.0,3.242772,1.699512,1.000000e+00,2.000000e+00,3.00000,4.000000,7.000000
DMDHRGND,4115.0,1.564277,0.495912,1.000000e+00,1.000000e+00,2.00000,2.000000,2.000000
DMDHRAGZ,4124.0,2.539525,0.641094,1.000000e+00,2.000000e+00,2.00000,3.000000,4.000000
DMDHREDZ,3746.0,2.171383,0.660132,1.000000e+00,2.000000e+00,2.00000,3.000000,3.000000
DMDHRMAZ,4020.0,1.381095,0.681421,1.000000e+00,1.000000e+00,1.00000,2.000000,3.000000
DMDHSEDZ,2127.0,2.275035,0.694050,1.000000e+00,2.000000e+00,2.00000,3.000000,3.000000
WTINT2YR,11933.0,27404.135674,19449.155209,4.584463e+03,1.433175e+04,21670.18597,33831.331556,170968.343177
WTMEC2YR,11933.0,27404.135674,27962.962514,5.397605e-79,5.397605e-79,21717.84916,38341.150005,227108.296958
SDMVSTRA,11933.0,179.918294,4.309624,1.730000e+02,1.760000e+02,180.00000,184.000000,187.000000
SDMVPSU,11933.0,1.491746,0.499953,1.000000e+00,1.000000e+00,1.00000,2.000000,2.000000
INDFMPIR,9892.0,2.708174,1.670119,5.397605e-79,1.180000e+00,2.50000,4.500000,5.000000

The dataset has 11 933 rows and 27 columns.

Check for missing values in the dataset

In [7]:
df.isnull().sum()

SEQN            0
SDDSRVYR        0
RIDSTATR        0
RIAGENDR        0
RIDAGEYR        0
RIDAGEMN    11556
RIDRETH1        0
RIDRETH3        0
RIDEXMON     3073
RIDEXAGM     9146
DMQMILIZ     3632
DMDBORN4       19
DMDYRUSR    10058
DMDEDUC2     4139
DMDMARTZ     4141
RIDEXPRG    10430
DMDHHSIZ        0
DMDHRGND     7818
DMDHRAGZ     7809
DMDHREDZ     8187
DMDHRMAZ     7913
DMDHSEDZ     9806
WTINT2YR        0
WTMEC2YR        0
SDMVSTRA        0
SDMVPSU         0
INDFMPIR     2041
dtype: int64

In [8]:
print(df['RIDAGEYR'].value_counts())  # Frequency of age in years

80.0    525
8.0     257
5.0     246
4.0     229
12.0    228
       ...
79.0     82
23.0     82
47.0     76
78.0     73
20.0     71
Name: RIDAGEYR, Length: 81, dtype: int64